frontend:
  image: "nginx:latest"
  replicas: 2
  serviceType: "ClusterIP"
  servicePort: 80

backend:
  image: "node:14"
  replicas: 3
  serviceType: "ClusterIP"
  servicePort: 8080

database:
  image: "mysql:5.7"
  replicas: 1
  serviceType: "ClusterIP"
  servicePort: 3306
  storage:
    size: 10Gi

