apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-database
spec:
  type: {{ .Values.database.serviceType }}
  ports:
    - port: {{ .Values.database.servicePort }}
  selector:
    app: {{ .Release.Name }}-database
